services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306

    environment:
      - MYSQL_DATABASE=blogapp
      - MYSQL_ROOT_PASSWORD=${MYSQL_DB_PASSWORD}

    volumes:
      - ../mysqldatablog:/var/lib/mysql

  django:
    build: .
    command: ./wait-for-it.sh mysql:3306 -- ./entrypoint.sh

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    # environment:
    #   - DB_HOST=mysql
    #   - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}

    depends_on:
      - mysql


    restart: on-failure


