services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306

    environment:
      - MYSQL_DATABASE=blogapp
      - MYSQL_ROOT_PASSWORD=${MYSQL_DB_PASSWORD}

    volumes:
      - ../mysqldatablog:/var/lib/mysql

  django:
    build: .
    command: ./wait-for-it.sh mysql:3306 -- ./entrypoint.sh


    environment:
      - HOST=mysql
      - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}


    volumes:
      - .:/app


    depends_on:
      - mysql


    restart: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/static
      - ./media:/app/media
    depends_on:
      - django
    restart: always



